import type { Metadata } from "next";
import "../globals.css";
import { Header } from "@/widgets/header/header";
import { Sidebar } from "@/widgets/sidebar/sidebar";
import { requireAdmin } from "@/shared/lib/guards";
import { SpeedInsights } from "@vercel/speed-insights/next"


export const metadata: Metadata = {
  title: "Генерация расписания",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  await requireAdmin();
  return (
    <html lang="en" className="h-full">
      <body className="h-screen overflow-hidden flex gap-5">
        <div className="">
          <Sidebar />
        </div>

        <div className="flex-1 flex flex-col gap-2.5 min-h-0 mr-2">
          <Header />
          <main className="flex-1 overflow-y-auto min-h-0 pb-1">
            {children}
          </main>
        </div>
        <SpeedInsights />
      </body>
    </html>
  );
}