import type { Metadata } from "next";
import "../globals.css";


export const metadata: Metadata = {
  title: "Генерация расписания",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full sidebar-scroll">
      <body className="min-h-full flex p-2 gap-5">
        <main className="w-full sidebar-scroll">
          {children}
        </main>
      </body>
    </html>
  );
}
